### ISSUE TITLE
Do not output null values

### ISSUE THREAD

**Issue by bwarner22** [ritterim/descriptor#22]
For example:

"Methods": [{
"Parameters": [
{
"Rel": null,
"Uri": null,
"Verb": null,
"Description": "The monthly dollar amount of the benchmark plan.",
"Name": "BenchmarkPlanValue",
"Type": "decimal"

**Comment by khalidabuhakmeh** [comment]
Was able to resolve this with this https://github.com/ritterim/quoteengine-api/pull/261

Not sure if we need to do this anymore, or if Bill wants to add anymore extensibility. I'll leave it up to him.

**Comment by williambogaiv** [comment]
@khalidabuhakmeh's link corrects the issue specific to the quote engine app. Descriptor allows customization during formatting using the `Format` overload: https://github.com/ritterim/descriptor/blob/9bb095c7df0215fe5b30b7974e36a6c31934f9f3/src/Descriptor.Formatters.Json/JsonFormatter.cs#L15-L18
