### ISSUE TITLE
Add Web Specific Extensions

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/descriptor#4]
Currently, discriptors can only describe methods, models, and parameters. We also need support for web specific values, like (but not limited to):

- Url / Href
- Rel

**Comment by williambogaiv** [comment]
See [my comment](https://github.com/ritterim/descriptor/pull/8#issuecomment-83093320) and provide any thoughts about the proposal. Also related to #3 with respect to separate projects. Maybe I'm not seeing a potential pitfall with the separate-project approach.

**Comment by williambogaiv** [comment]
@khalidabuhakmeh: the separate-project/NuGet idea was sparked after realizing I would most-likely use [Json.NET](http://www.newtonsoft.com/json) to serialize the collection of descriptors. No point in requiring this dependency for someone who is only going to use Markdown, etc.
